%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_ReadOnlyProperty
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_ReadOnlyProperty').
-ic_compiled("4_2_25").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/ReadOnlyProperty:1.0",
                   "ReadOnlyProperty",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/ReadOnlyProperty:1.0".

%% returns name
name() -> "CosPropertyService_ReadOnlyProperty".



