%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventChannelAdmin_AlreadyConnected
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventChannelAdmin_AlreadyConnected').
-ic_compiled("4_2_25").


-include("CosEventChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0",
                   "AlreadyConnected",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0".

%% returns name
name() -> "CosEventChannelAdmin_AlreadyConnected".



