%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventComm_Disconnected
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventComm_Disconnected').
-ic_compiled("4_2_25").


-include("CosEventComm.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventComm/Disconnected:1.0","Disconnected",
                   []}.

%% returns id
id() -> "IDL:omg.org/CosEventComm/Disconnected:1.0".

%% returns name
name() -> "CosEventComm_Disconnected".



