%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContext_InvalidName
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContext_InvalidName').
-ic_compiled("4_2_25").


-include("CosNaming_NamingContext.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0",
                   "InvalidName",[]}.

%% returns id
id() -> "IDL:omg.org/CosNaming/NamingContext/InvalidName:1.0".

%% returns name
name() -> "CosNaming_NamingContext_InvalidName".



