%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Terminator
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_TERMINATOR_HRL).
-define(COSTRANSACTIONS_TERMINATOR_HRL, true).




-endif.


