%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_NoTransaction
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_NoTransaction').
-ic_compiled("4_2_25").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/NoTransaction:1.0",
                   "NoTransaction",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/NoTransaction:1.0".

%% returns name
name() -> "CosTransactions_NoTransaction".



