%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PushSupplier
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PUSHSUPPLIER_HRL).
-define(COSEVENTCOMM_PUSHSUPPLIER_HRL, true).




-endif.


