%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTimerEvent
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTIMEREVENT_HRL).
-define(OE_COSTIMEREVENT_HRL, true).




-endif.


