%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ChannelNotFound
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ChannelNotFound').
-ic_compiled("4_2_25").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/ChannelNotFound:1.0",
                   "ChannelNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ChannelNotFound:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ChannelNotFound".



