%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: OrberApp_IFR
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ORBERAPP_IFR_HRL).
-define(ORBERAPP_IFR_HRL, true).




-endif.


