%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_Filter
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_FILTER_HRL).
-define(COSNOTIFYFILTER_FILTER_HRL, true).




-endif.


