%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_PushConsumer
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_PUSHCONSUMER_HRL).
-define(COSNOTIFYCOMM_PUSHCONSUMER_HRL, true).




-endif.


