%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotificationComm_Event
%% Source: /net/isildur/ldisk/daily_build/r14b01_prebuild_opu_o.2010-12-07_16/otp_src_R14B01/lib/cosNotification/src/cosNotificationAppComm.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFICATIONCOMM_EVENT_HRL).
-define(OE_COSNOTIFICATIONCOMM_EVENT_HRL, true).




-endif.


